### ISSUE TITLE
Zope does no longer handle `string:$$` correctly

### ISSUE THREAD

**Issue by viktordick** [zopefoundation/zope.tales#14]
I'm not sure if I should post this here, since I can not reproduce the error using only zope.tales, but if running in a complete Zope 4.0b9 (which requires tales 4.3), I run into the error that

    <div tal:content="string:Test$$"></div>

renders to give me

    <div>Test$$</div>

instead of

    <div>Test$</div>

If, instead, I install tales into a virtualenv without any other dependencies and run the following code (inspired by a test):

    import zope.tales.engine

    class Data(object):

        def __init__(self, **kw):
            self.__dict__.update(kw)

        def __getattr__(self, name):
            # Let linters (like pylint) know this is a dynamic class and they shouldn't
            # emit "Data has no attribute" errors
            return object.__getattribute__(self, name)

        def __repr__(self):
            return self.name

        __str__ = __repr__

    zope.tales.engine.Engine.compile('string:Test$$')(Data(vars={}))

I obtain

    Test$

as expected.
I have not yet dug any deeper where exactly the error occurs, but wanted to post my finding here since this might be critical for a stable release.

**Comment by mgedmin** [comment]
> I have not yet dug any deeper where exactly the error occurs, but wanted to post my finding here since this might be critical for a stable release.

It might be a good idea to post this to https://github.com/zopefoundation/Zope/issues

**Comment by viktordick** [comment]
All right, it seems that PageTemplates no longer use zope.tales to render, but chameleon.tales (not sure why it is still part of the requirements list). With chameleon.tales I can also reproduce the issue, so I will post it there and close this.
