### ISSUE TITLE
Link to specification is dead

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.tales#4]
The README references http://wiki.zope.org/ZPT/TALESSpecification13 which no longer exists.

**Comment by mgedmin** [comment]
The Internet Archive has a copy: http://web.archive.org/web/20120617054712/http://wiki.zope.org/ZPT/TALESSpecification13

**Comment by jamadden** [comment]
There's also a little bit of overlap with the [Chameleon documentation for TALES](https://chameleon.readthedocs.io/en/latest/reference.html#expressions-tales).

**Comment by davisagli** [comment]
There is also a [summary of TALES in the Zope Book](https://docs.zope.org/zope2/zope2book/AppendixC.html#tales-overview)

**Comment by icemac** [comment]
Thank you all for providing links to fix this issue.
